export  {default as mainImg} from "./imgs/HeaderPictureLight.png"
export  {default as bedSvg} from "./svgs/Bed.svg"
export  {default as calendarSvg} from "./svgs/Calenar.svg"
export  {default as adultSvg} from "./svgs/Adult.svg"
export  {default as kidSvg} from "./svgs/kid.svg"
export  {default as nameSvg} from "./svgs/Name.svg"
export  {default as phoneSvg} from "./svgs/Phone.svg"
export  {default as walletSvg} from "./svgs/wallet.svg"
export  {default as bellSvg} from "./svgs/bell.svg"
export  {default as twinRoomImg} from "./svgs/smallRoomCard.svg"
export  {default as doubleRoomImg} from "./svgs/MediumRoomCard.svg"
export  {default as familyRoomImg} from "./svgs/big room card.svg"
export  {default as upArrow} from "./svgs/upArrow.svg"
export  {default as downArrow} from "./svgs/downArrow.svg"
